### ISSUE TITLE
Empty values bug

### ISSUE THREAD

**Issue by RPing** [RPing/influx-prompt#10]
influx-prompt
```
root> SHOW CONTINUOUS QUERIES
Traceback (most recent call last):
  File "/home/rpchen1228/.pyenv/versions/3.6.4/bin/influx-prompt", line 8, in <module>
    sys.exit(cli())
  File "/home/rpchen1228/.pyenv/versions/3.6.4/lib/python3.6/site-packages/influx_prompt/main.py", line 176, in cli
    influx_prompt.run_cli()
  File "/home/rpchen1228/.pyenv/versions/3.6.4/lib/python3.6/site-packages/influx_prompt/main.py", line 95, in run_cli
    arr = json_to_tabular_result(result)
  File "/home/rpchen1228/.pyenv/versions/3.6.4/lib/python3.6/site-packages/influx_prompt/tabular.py", line 27, in json_to_tabular_result
    values = series['values']
KeyError: 'values'
```

Official cli
```
> SHOW CONTINUOUS QUERIES
name: _internal
name query
---- -----

name: NOAA_water_database
name query
---- -----
> 
```

**Comment by RPing** [comment]
ref #1
