### ISSUE TITLE
Unicode Problem

### ISSUE THREAD

**Issue by wu-nerd** [RPing/influx-prompt#2]
Got an error running influx-prompt
``` python
Traceback (most recent call last):
  File "/home/op/dir/venv/bin/influx-prompt", line 11, in <module>
    sys.exit(cli())
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/main.py", line 171, in cli
    influx_prompt = InfluxPrompt(vars(args), password)
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/main.py", line 44, in __init__
    self.cli = self._build_cli()
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/main.py", line 102, in _build_cli
    lexer=PygmentsLexer(SqlLexer),
  File "/home/op/dir/venv/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 229, in create_prompt_layout
    assert isinstance(message, text_type), 'Please provide a unicode string.'
AssertionError: Please provide a unicode string.
```
After edit https://github.com/RPing/influx-prompt/blob/master/influx_prompt/main.py#L101 to
``` python
message=u'{0}> '.format(self.args['username'])
```
it works! 

But still get an error when SELECT result contains Chinese:

``` python
Traceback (most recent call last):
  File "/home/op/dir/venv/bin/influx-prompt", line 11, in <module>
    sys.exit(cli())
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/main.py", line 172, in cli
    influx_prompt.run_cli()
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/main.py", line 94, in run_cli
    arr = json_to_tabular_result(result)
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/tabular.py", line 33, in json_to_tabular_result
    longest_value_len
  File "/home/op/dir/venv/lib/python2.7/site-packages/influx_prompt/tabular.py", line 82, in _calculate_value_len
    value_len = len(str(value[index]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)
```

Linux 3.10.0-514.10.2.el7.x86_64
Python 2.7.5

**Comment by wu-nerd** [comment]
Reproduce in python 2.7.15, macOS 10.13.6 (17G65):

- run docker
``` bash
docker pull influxdb
docker run -p 8086:8086 -p 8083:8083 \
    -e INFLUXDB_ADMIN_ENABLED=true \
    influxdb
```

- create mydb
``` bash
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
```
- insert data
``` bash
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'test,key=值 value=0.64'
```
- run influxdb, got `AssertionError: Please provide a unicode string.`
- edit main.py, run influxdb, query data
``` mysql
use mydb
select * from test
```
got `UnicodeEncodeError: 'ascii' codec can't encode character u'\u503c' in position 0: ordinal not in range(128)`

---

Python 3.7.0 works fine. 
But python 3 is not installed by default on some distribution, like centOS 7 core.

**Comment by RPing** [comment]
You can use [0.1.0](https://github.com/RPing/influx-prompt/releases/tag/0.1.0) now :)
